(in-package #:eh)

(defun menu ()
  '((:link "/" :title "Главная")
    (:link "/about" :title "Обо-мне")
    (:link "/service" :title "Предоставляемые-услуги")
    (:link "/works" :title "Портфолио")
    (:link "/prices" :title "Цены-на-услуги")
    (:link "/customers" :title "Наши-клиенты")
    (:link "/facts" :title "Факты-о-рекламе")
    (:link "/faq" :title "FAQ")
    (:link "/specialty" :title "Специализация")
    (:link "/ad_outdoor" :title "Наружная реклама")
    (:link "/exhibition" :title "Выставочная-деятельность")
    (:link "/articles" :title "Статьи")
    (:link "/ad" :title "РЕКЛАМА")
    (:link "/ad_history" :title "История-рекламы")
    (:link "/ad_terminology" :title "Терминология-рекламы")
    (:link "/pr" :title "PR")
    (:link "/event_marketing" :title "Event-marketing")
    (:link "/what_pr" :title "Что-такое-PR?")
    (:link "/propaganda_pr" :title "Пропаганда-и-PR")
    (:link "/lisp" :title "Сайты-на-Lisp")
    (:link "/news" :title "Новости")
    (:link "/userful_links" :title "Полезные-ссылки")
    (:link "/contacts" :title "Контакты")
    (:link "/sitemap" :title "Карта-сайта")))

;; start
(restas:start '#:eh :port 2002)
(restas:debug-mode-on)
;; (restas:debug-mode-off)
(setf hunchentoot:*catch-errors-p* t)
